# https://docs.docker.com/reference/compose-file/extension/
x-dev-constants: &dev-constants
  PG_USER: &pg-user picms
  PG_PASS: &pg-pass pass
  PG_PORT: &pg-port 5432

services:
  picms:
    build:
      context: .
      dockerfile: Dockerfile
    init: true # to prevent zombie processes
    environment:
      <<: *dev-constants
      PICMS_CACHE_DIR: /workspaces/picms/.cache
      PICMS_PORT_MAIN: 9001
      PICMS_PORT_INSPECT: 9002
      PICMS_PORT_WEB: 9003
      # options: local, gcs, fake-gcs
      PICMS_STORAGE_TYPE: local
      PICMS_STORAGE_LOCAL_ORIGIN: "localhost:9003" # PICMS_PORT_WEB for development
      PICMS_STORAGE_FAKE_GCS_BUCKET: "devlopment"
    command: sleep infinity
    depends_on:
      postgres:
        condition: service_healthy
      gcs:
        condition: service_started
    volumes:
      - "..:/workspaces/picms"

  # https://hub.docker.com/_/postgres#-via-docker-compose
  postgres:
    image: postgres:18.4 # TODO: specify hash
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: *pg-pass
      POSTGRES_USER: *pg-user
    healthcheck:
      test: pg_isready
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 5s

  # https://hub.docker.com/r/dbgate/dbgate
  dbgate:
    image: dbgate/dbgate:7.2.1 # TODO: specify hash
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CONNECTIONS: postgres

      # postgress
      LABEL_postgres: Postgres
      SERVER_postgres: postgres
      USER_postgres: *pg-user
      PASSWORD_postgres: *pg-pass
      PORT_postgres: *pg-port
      ENGINE_postgres: postgres@dbgate-plugin-postgres

  # https://github.com/fsouza/fake-gcs-server
  gcs:
    image: fsouza/fake-gcs-server
    environment:
      FAKE_GCS_PUBLIC_HOST: gcs
      FAKE_GCS_SCHEME: http
    volumes:
      - "../.cache/gcs:/storage"
