/**
 * This file is the entry point for the React app, it sets up the root
 * element and renders the App component to the DOM.
 *
 * It is included in `src/index.html`.
 */

import { createRoot } from "react-dom/client";
import { App } from "@/App";

// biome-ignore lint: generated by `bun init`
const elem = document.getElementById("root")!;
const app = <App />;

// https://bun.com/docs/bundler/hot-reloading#import-meta-hot-data
// biome-ignore lint: generated by `bun init`
(import.meta.hot.data.root ??= createRoot(elem)).render(app);
