import { describe, expect, spyOn, test } from "bun:test";
import { ERROR_CODE } from "../../constants";
import type { Revision } from "../../domains/revision/entity";
import { _TEST as REVISION_REPOSITORY_TEST } from "../../domains/revision/repository";
import { _TEST as SHARED_REPOSITORY_TEST } from "../../domains/shared/repository";
import { issueSignedUrl } from "./usecases";

const { FakeSharedStorage } = SHARED_REPOSITORY_TEST;
const { FakeRevisionDatabase } = REVISION_REPOSITORY_TEST;

const VALID_REVISION: Revision = {
	id: Bun.randomUUIDv7(),
	workId: Bun.randomUUIDv7(),
	createdAt: new Date(),
};

describe("issueSignedUrl", () => {
	test("returns url generated by revisionStorage if all checks pass", async () => {
		const revisionDatabase = new FakeRevisionDatabase();
		spyOn(revisionDatabase, "findById").mockImplementation(
			() => VALID_REVISION,
		);

		const revisionStorage = new FakeSharedStorage();
		spyOn(revisionStorage, "checkAvailability").mockImplementation(() => true);
		const dummyExpectedUrl = "https://example.com/dummy/url";
		spyOn(revisionStorage, "issueSignedUrl").mockImplementation(
			() => dummyExpectedUrl,
		);

		const url = await issueSignedUrl(VALID_REVISION.id, {
			revisionDatabase,
			revisionStorage,
		});

		expect(url).toBe(dummyExpectedUrl);
	});

	test("do not issue url if revision is not found", async () => {
		const revisionDatabase = new FakeRevisionDatabase();
		spyOn(revisionDatabase, "findById").mockImplementation(() => undefined);
		const revisionStorage = new FakeSharedStorage();
		const spy = spyOn(revisionStorage, "issueSignedUrl");

		expect(async () => {
			await issueSignedUrl(VALID_REVISION.id, {
				revisionDatabase,
				revisionStorage,
			});
		}).toThrow(ERROR_CODE.NOT_FOUND);

		expect(spy).toBeCalledTimes(0);
	});

	test("do not issue url if revision is too old", () => {
		const revision: Revision = {
			...VALID_REVISION,
			createdAt: new Date(0),
		};
		const revisionDatabase = new FakeRevisionDatabase();
		spyOn(revisionDatabase, "findById").mockImplementation(() => revision);
		const revisionStorage = new FakeSharedStorage();
		const spy = spyOn(revisionStorage, "issueSignedUrl");

		expect(async () => {
			await issueSignedUrl(revision.id, {
				revisionDatabase,
				revisionStorage,
			});
		}).toThrow(ERROR_CODE.REQUEST_TIMEOUT);

		expect(spy).toBeCalledTimes(0);
	});

	test("do not issue url if storage is not available", () => {
		const revision: Revision = {
			...VALID_REVISION,
		};
		const revisionDatabase = new FakeRevisionDatabase();
		spyOn(revisionDatabase, "findById").mockImplementation(() => revision);
		const revisionStorage = new FakeSharedStorage();
		spyOn(revisionStorage, "checkAvailability").mockImplementation(() => false);
		const spy = spyOn(revisionStorage, "issueSignedUrl");

		expect(async () => {
			await issueSignedUrl(revision.id, {
				revisionDatabase,
				revisionStorage,
			});
		}).toThrow(ERROR_CODE.CONFLICT);

		expect(spy).toBeCalledTimes(0);
	});
});
