on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-devcontainer
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          push: true
      - run: devcontainer up
      - run: devcontainer exec bun run lint
      - run: devcontainer exec bun run test
      - run: devcontainer exec bun run build
